PoliziaMunicipale-GestioneContravvenzioni/Models/Verbale.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PoliziaMunicipale_GestioneContravvenzioni.Models
{
    public class Verbale
    {
        [Display(Name = "Nr")]
        public int ID_Verbale { get; set; }
        [Display(Name = "Agente")]
        public string NominativoAgente { get; set; }
        [DataType(DataType.DateTime)]
        [Display(Name = "Data violazione")]
        public DateTime DataViolazione { get; set; }
        [Display(Name = "Indirizzo")]
        public string IndirizzoViolazione { get; set; }
        [DataType(DataType.DateTime)]
        [Display(Name = "Data trascrizione")]
        public DateTime DataTrascrizioneVerbale { get; set; }
        [DataType(DataType.Currency)]
        public decimal Importo { get; set; }
        [Display(Name = "Decurtamento punti")]
        public int DecurtamentoPunti { get; set; }
        public int ID_Violazione { get; set; }
        [Display(Name = "TipoViolazione")]
        public string TipoViolazione { get; set; }
        public int ID_Anagrafica { get; set; }
        [Display(Name = "Trasgressore")]
        public string NomeCognomeTrasgressore { get; set; }

        public static List<Verbale> ListaVerbali = new List<Verbale>();
    }
}

PoliziaMunicipale-GestioneContravvenzioni/Controllers/VerbaleController.cs
using PoliziaMunicipale_GestioneContravvenzioni.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace PoliziaMunicipale_GestioneContravvenzioni.Controllers
{
    public class VerbaleController : Controller
    {
        // GET: Verbale
        public ActionResult Lista()
        {
            SqlConnection con = Shared.getConToDB();
            try
            {
                Verbale.ListaVerbali.Clear();
                con.Open();
                string tsql = "SELECT * FROM Verbale AS V JOIN TipoViolazione AS tV " +
                    "ON tV.ID_Violazione = V.ID_Violazione JOIN Anagrafica AS A ON A.ID_Anagrafica = V.ID_Anagrafica " +
                    "ORDER BY DataTrascrizioneVerbale DESC";
                SqlDataReader reader = Shared.getReader(tsql, con);

                if (reader.HasRows)
                {
                    while (reader.Read())
                    {
                        Verbale v = new Verbale();
                        v.ID_Verbale = Convert.ToInt32(reader["ID_Verbale"]);
                        v.NominativoAgente = reader["NominativoAgente"]+"";
                        v.DataViolazione = Convert.ToDateTime(reader["DataViolazione"]);
                        v.IndirizzoViolazione = reader["IndirizzoViolazione"]+"";
                        v.DataTrascrizioneVerbale = Convert.ToDateTime(reader["DataTrascrizioneVerbale"]);
                        v.Importo = Convert.ToDecimal(reader["importo"]);
                        v.DecurtamentoPunti = Convert.ToInt32(reader["DecurtamentoPunti"]);
                        v.ID_Violazione = Convert.ToInt32(reader["ID_Violazione"]);
                        v.ID_Anagrafica = Convert.ToInt32(reader["ID_Anagrafica"]);
                        v.TipoViolazione = reader["Descrizione"]+"";
                        v.NomeCognomeTrasgressore = reader["Nome"] + " " + reader["Cognome"];

                        Verbale.ListaVerbali.Add(v);
                        
                    }
                }
                con.Close();
            }
            catch (Exception ex)
            {
                con.Close();
            }
            return View(Verbale.ListaVerbali);
        }
        public ActionResult Archivia()
        {
            SqlConnection con = Shared.getConToDB();
            List<SelectListItem> listaViolazioni = new List<SelectListItem>();
            try
            {
                con.Open();
                string tsql = "SELECT V.ID_Violazione, Descrizione FROM Verbale AS V JOIN TipoViolazione AS tV "+
                    " ON tV.ID_Violazione = V.ID_Violazione JOIN Anagrafica AS A ON A.ID_Anagrafica = V.ID_Anagrafica "+
                    " GROUP BY  V.ID_Violazione, Descrizione";
                SqlDataReader reader = Shared.getReader(tsql, con);

                
                if (reader.HasRows)
                {

                    while (reader.Read())
                    {
                       SelectListItem item = new SelectListItem();
                        item.Text = reader["Descrizione"].ToString();
                        item.Value = reader["ID_Violazione"].ToString();
                        listaViolazioni.Add(item);
                    }
                }
                con.Close();
            }
            catch (Exception ex)
            {
                con.Close();
            }
            ViewBag.TipoViolazioni = listaViolazioni;
            ViewBag.ListaTrasgressoriCercarti = "";


            return View();
        }

        public ActionResult Cerca(string Cerca)
        {
            SqlConnection con2 = Shared.getConToDB();
            List<SelectListItem> listaTrasgressoriCercati = new List<SelectListItem>();
            try
            {
                con2.Open();

                string tsql = $"SELECT * FROM Anagrafica WHERE Nome = '%{Cerca}%' OR Cognome = '%{Cerca}%'";
                SqlDataReader reader = Shared.getReader(tsql, con2);


                if (reader.HasRows)
                {

                    while (reader.Read())
                    {
                        SelectListItem item = new SelectListItem();
                        item.Text = reader["Descrizione"].ToString();
                        item.Value = reader["ID_Violazione"].ToString();
                        listaTrasgressoriCercati.Add(item);
                    }
                }
                con2.Close();
            }
            catch (Exception ex)
            {
                con2.Close();
            }
            ViewBag.ListaTrasgressoriCercarti = listaTrasgressoriCercati;

            return View();

        }
    } 
}

PoliziaMunicipale-GestioneContravvenzioni/Views/Verbale/Archivia.cshtml
@model PoliziaMunicipale_GestioneContravvenzioni.Models.Verbale

@{
    ViewBag.Title = "Archivia";
}

<h2>Archivia</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Verbale</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID_Verbale, htmlAttributes: new { @class = "control-label col-md-2" })

    <div class="form-group">
        @Html.LabelFor(model => model.NominativoAgente, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NominativoAgente, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NominativoAgente, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DataViolazione, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DataViolazione, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DataViolazione, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IndirizzoViolazione, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.IndirizzoViolazione, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IndirizzoViolazione, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DataTrascrizioneVerbale, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DataTrascrizioneVerbale, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DataTrascrizioneVerbale, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Importo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Importo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Importo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DecurtamentoPunti, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DecurtamentoPunti, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DecurtamentoPunti, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.ID_Violazione, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID_Violazione, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID_Violazione, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.TipoViolazione, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("TipoViolazioni", new SelectList(ViewBag.TipoViolazioni, "Value", "Text"), new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.TipoViolazione, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.ID_Anagrafica, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID_Anagrafica, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID_Anagrafica, "", new { @class = "text-danger" })
            </div>
        </div>*@



    @using (Html.BeginForm("Cerca", "Verbale", FormMethod.Post))
    {

        <div class="form-group">
            @Html.Label("Cerca trasgressore", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("CercaTrasgressore", "", htmlAttributes: new { @class = "form-control" })

                <button type="submit" class="btn">Cerca</button>
            </div>
        </div>
    }

    <div class="form-group">
        @Html.LabelFor(model => model.NomeCognomeTrasgressore, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Trasgressore", new SelectList(ViewBag.ListaTrasgressoriCercarti, "Value", "Text"), new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.NomeCognomeTrasgressore, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Archivia" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Ritorna alla Lista", "Lista" , new { controller = "Verbale" })
</div>

PoliziaMunicipale-GestioneContravvenzioni/Views/Verbale/Lista.cshtml
@model IEnumerable<PoliziaMunicipale_GestioneContravvenzioni.Models.Verbale>

@{
    ViewBag.Title = "Verbali";
}

<h2>Verbali</h2>

<p>
    @Html.ActionLink("Archivia nuovo verbale", "Archivia", new { } , htmlAttributes: new { @class = "btn" , @style = "background-color: #292b2c; color: white;" })
</p>
<table class="table table-bordered img-rounded " style="background-color:white;">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ID_Verbale)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NominativoAgente)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataViolazione)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IndirizzoViolazione)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataTrascrizioneVerbale)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Importo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DecurtamentoPunti)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoViolazione)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NomeCognomeTrasgressore)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ID_Verbale)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NominativoAgente)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataViolazione)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IndirizzoViolazione)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataTrascrizioneVerbale)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Importo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DecurtamentoPunti)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TipoViolazione)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NomeCognomeTrasgressore)
        </td>
        <td style="min-width:130px">
            @Html.ActionLink("Modifica", "Edit", new {  id=item.ID_Verbale }, htmlAttributes: new {@class="btn btn-sm btn-primary"}) 
            @*@Html.ActionLink("Details", "Details", new { id = item.ID_Verbale }) |*@
            @Html.ActionLink("X", "Delete", new { id = item.ID_Verbale }, htmlAttributes: new { @class = "btn btn-sm btn-danger" })
        </td>
    </tr>
}

</table>